package stringrotator.stringrotator;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URISyntaxException;

import javax.swing.JOptionPane;
/**
 *
 * @author Aziz shahiwala
 */
public class CanvasWindowUI extends javax.swing.JFrame {
    public static boolean halt = false;
    public static float speed = 1;
    public Process process;
    MainWindowUI mainWindowUI;
    Thread TerminalThread;
    public boolean MenuRunning = false;
    public boolean TerminalRunning, PNGMode;
    public static String SharedText_path = "";
    public String Sharedpython_path = "";
    //Keeps updating manual text input.
    StringBuilder manualtextinputbuffer;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CanvasWindowUI.class.getName());

    /**
     * Creates new form CanvasWindowUI
     */
    public CanvasWindowUI(MainWindowUI mainwindowui) {
        this.mainWindowUI = mainwindowui;
        this.manualtextinputbuffer = mainwindowui.manualtextinputbuffer;
        this.PNGMode = mainwindowui.PNGMode;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        canvas_scroll_pane = new javax.swing.JScrollPane();
        canvas_scrollitems = new javax.swing.JList<>();
        canvas_speed_label = new javax.swing.JLabel();
        canvas_close = new javax.swing.JButton();
        canvas_halt = new javax.swing.JToggleButton();
        canvas_label = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setAlwaysOnTop(true);

        canvas_scrollitems.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        canvas_scrollitems.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "0.25x", "0.5x", "1x (normal)", "2x", "3x", "4x" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        canvas_scrollitems.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                canvas_scrollitemsValueChanged(evt);
            }
        });
        canvas_scroll_pane.setViewportView(canvas_scrollitems);

        canvas_speed_label.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        canvas_speed_label.setForeground(new java.awt.Color(0, 153, 153));
        canvas_speed_label.setText("Speed: ");

        canvas_close.setBackground(new java.awt.Color(255, 51, 51));
        canvas_close.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        canvas_close.setText("End");
        canvas_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canvas_closeActionPerformed(evt);
            }
        });

        canvas_halt.setBackground(new java.awt.Color(255, 204, 0));
        canvas_halt.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        canvas_halt.setText("Pause");
        canvas_halt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        canvas_halt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        canvas_halt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canvas_haltActionPerformed(evt);
            }
        });

        canvas_label.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        canvas_label.setForeground(new java.awt.Color(0, 153, 153));
        canvas_label.setText("Viewing options: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(canvas_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(canvas_halt, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(canvas_close, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(canvas_speed_label)
                .addGap(18, 18, 18)
                .addComponent(canvas_scroll_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(canvas_label, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(canvas_halt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(canvas_speed_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(canvas_close, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)))
                .addGap(0, 28, Short.MAX_VALUE))
            .addComponent(canvas_scroll_pane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void canvas_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canvas_closeActionPerformed
        try {

        File tempFile = new File("Temp.txt");
        File configFile = new File(".config.txt");

        if (tempFile.exists()) tempFile.delete();
        if (configFile.exists()) configFile.delete();
        
        mainWindowUI.appCanvas_run.setEnabled(false);
        // Kill all python processes in started terminal
        Runtime.getRuntime().exec("taskkill /F /IM cmd.exe /T");    
    } catch (IOException e) {
        e.printStackTrace();
    }
    catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Could not cleanup catche files:\n" + e.getMessage(), "File Deletion Error", JOptionPane.ERROR_MESSAGE);
    }
        mainWindowUI.appCanvas_run.setEnabled(true);
        process.destroy();
        this.dispose();
    }//GEN-LAST:event_canvas_closeActionPerformed

    private void canvas_haltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canvas_haltActionPerformed
        
        // TODO add your handling code here:
        try{
            FileWriter fw = new FileWriter(".config.txt");
BufferedWriter bw = new BufferedWriter(fw);

            if(canvas_halt.isSelected())
            {
                canvas_halt.setBackground(new java.awt.Color(255, 204, 0));
                halt = true;
            }
            else{
                canvas_halt.setBackground(new java.awt.Color(102, 255, 51));
                halt = false;
            } 
                
            bw.write("Halt = "+halt+"\n");
            bw.write("Speed = "+speed+"\n");
            bw.write("Save = "+mainWindowUI.Save+"\n");     
            bw.flush();
            fw.flush();
            bw.close();
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e,"Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_canvas_haltActionPerformed
    private void canvas_scrollitemsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_canvas_scrollitemsValueChanged
        // TODO add your handling code here:
        try{
            FileWriter fw = new FileWriter(".config.txt");
    BufferedWriter bw = new BufferedWriter(fw);
    int index = canvas_scrollitems.getSelectedIndex();
        switch(index){
            case 0:
            speed = 0.25f;
            break;
            case 1:
            speed = 0.5f;
            break;
            case 2:
            speed = 1;
            break;
            case 3:
            speed = 2;
            break;
            case 4:
            speed = 3;
            break;
            case 5:
            speed = 4;
            break;
            default:
            speed = 1;
        }

        bw.write("Halt = "+halt+"\n");
        bw.write("Speed = "+speed+"\n");  
        bw.write("Save = "+mainWindowUI.Save+"\n"); 
        fw.flush();   
        bw.flush(); 
        bw.close();
    } catch(IOException e){
        JOptionPane.showMessageDialog(null, e, "IO exception",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_canvas_scrollitemsValueChanged

    protected void startProcess() {
    try {
        ProcessBuilder pb;
        String TempString = manualtextinputbuffer.toString();
        File file = new File("Temp.txt");

        FileWriter writer = new FileWriter(file);
        writer.write(TempString);
        writer.close();

        
        SharedText_path = file.getAbsolutePath();
        
        mainWindowUI.iscanvasrunning = true;
        //Here, 1 inside processbuilder means Mode: Create and Run.

            String pythonExecutable = "python";

            // Dynamically determine the path to your Python scripts (resources folder)
            File pythonScriptsDir = null;
            try {
                // Get the directory of the currently executing JAR file
                String jarPath = CanvasWindowUI.class.getProtectionDomain().getCodeSource().getLocation().toURI().getPath();
                File currentDir = new File(jarPath).getParentFile();

                pythonScriptsDir = new File(currentDir, "resources");
                
                if (!pythonScriptsDir.exists()) {
                    File projectRoot = new File(currentDir.getAbsolutePath().split("target")[0]);
                    pythonScriptsDir = new File(projectRoot, "src" + File.separator + "main" + File.separator + "resources");
                }


            } catch (URISyntaxException e) {
                JOptionPane.showMessageDialog(null, "Error getting JAR path: " + e.getMessage(), "Path Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (!pythonScriptsDir.exists() || !pythonScriptsDir.isDirectory()) {
                JOptionPane.showMessageDialog(null, "Python resources directory not found at: " + pythonScriptsDir.getAbsolutePath(), "Configuration Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String runnerPath = new File(pythonScriptsDir, "Runner.py").getAbsolutePath();
            pythonExecutable = "python";
        if (PNGMode) {
                pb = new ProcessBuilder(
                    "cmd.exe", "/c", "start", "cmd.exe", "/k",
                    pythonExecutable + " \"" + runnerPath + "\" \"" + mainWindowUI.PNGSelcted.getAbsolutePath() + "\" 2"
                );
                mainWindowUI.appCanvas_load.setEnabled(false);
            } else {
                System.out.println("Using text file: " + SharedText_path);
                pb = new ProcessBuilder(
                    "cmd.exe", "/c", "start", "cmd.exe", "/k",
                    pythonExecutable + " \"" + runnerPath + "\" \"" + SharedText_path + "\" 1"
                );
            }
            pb.redirectErrorStream(true);
        process = pb.start();
            
        MenuRunning = true;
        BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
        String line;
        while ((line = reader.readLine()) != null) {
            System.out.println(line);
        }
        repaint();
        process.waitFor();
        if (!process.isAlive()) {
            this.dispose();
            mainWindowUI.appCanvas_run.setEnabled(false);
            mainWindowUI.appCanvas_load.setEnabled(true);
            mainWindowUI.iscanvasrunning = false;
        }

    } catch (IOException exc) {
        JOptionPane.showMessageDialog(null, exc, "IO Error", JOptionPane.ERROR_MESSAGE);
    } catch (InterruptedException exc) {
        JOptionPane.showMessageDialog(null, exc, "Interrupted", JOptionPane.ERROR_MESSAGE);
        Thread.currentThread().interrupt();
    } finally {
        try {
            MenuRunning = false;
            if (TerminalThread != null) TerminalThread.join();
        } catch (InterruptedException e) {
            JOptionPane.showMessageDialog(null, e, "Thread Join Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
    MainWindowUI main = new MainWindowUI(); // create main window instance
    CanvasWindowUI canvas = new CanvasWindowUI(main); // pass it
        main.CleanUI();
        canvas.setVisible(true);
});
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton canvas_close;
    private javax.swing.JToggleButton canvas_halt;
    private javax.swing.JLabel canvas_label;
    private javax.swing.JScrollPane canvas_scroll_pane;
    private javax.swing.JList<String> canvas_scrollitems;
    private javax.swing.JLabel canvas_speed_label;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}