package stringrotator.stringrotator;
import java.io.FileWriter;
import java.io.IOException;
import java.io.BufferedWriter;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author Aziz shahiwala
 */
public class MainWindowUI extends javax.swing.JFrame {
    public boolean PNGMode = false ,iscanvasrunning = false; 
    public boolean Save = false;
    public File PNGSelcted = null;
    CanvasWindowUI canvaswindowui = null;
    public JFileChooser chooser;
    public FileWriter config = null;
    StringBuilder manualtextinputbuffer;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainWindowUI.class.getName());

    /**
     * Creates new form UI
     */
    public MainWindowUI() {
        manualtextinputbuffer = new StringBuilder("Input");
        initComponents();
        CleanUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manualTextInput = new javax.swing.JTextField();
        appCanvas_load = new javax.swing.JButton();
        appCanvas_run = new javax.swing.JButton();
        appCanvas_saveoption = new javax.swing.JButton();
        appCanvas_loadPNG = new javax.swing.JButton();
        appCanvas_extrasLabel = new javax.swing.JLabel();
        appCanvas_imgpathlabel = new javax.swing.JLabel();

        jLabel1.setText("Rotation options");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("String rotator ~Aziz Juzar Shahiwala");
        setResizable(false);

        manualTextInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        manualTextInput.setText("Input");
        manualTextInput.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        manualTextInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualTextInputActionPerformed(evt);
            }
        });

        appCanvas_load.setBackground(new java.awt.Color(255, 255, 204));
        appCanvas_load.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        appCanvas_load.setForeground(new java.awt.Color(153, 153, 0));
        appCanvas_load.setText("Load");
        appCanvas_load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appCanvas_loadActionPerformed(evt);
            }
        });

        appCanvas_run.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        appCanvas_run.setForeground(new java.awt.Color(51, 51, 255));
        appCanvas_run.setText("Run");
        appCanvas_run.setEnabled(false);
        appCanvas_run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appCanvas_runActionPerformed(evt);
            }
        });

        appCanvas_saveoption.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        appCanvas_saveoption.setText("Save as GIF");
        appCanvas_saveoption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appCanvas_saveoptionActionPerformed(evt);
            }
        });

        appCanvas_loadPNG.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        appCanvas_loadPNG.setText("Upload your own PNG");
        appCanvas_loadPNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appCanvas_loadPNGActionPerformed(evt);
            }
        });

        appCanvas_extrasLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        appCanvas_extrasLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appCanvas_extrasLabel.setText("Extra:");

        appCanvas_imgpathlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(appCanvas_load, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(appCanvas_run, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(manualTextInput, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(appCanvas_extrasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(appCanvas_saveoption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(appCanvas_loadPNG, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))))
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(appCanvas_imgpathlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manualTextInput, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(appCanvas_load, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(appCanvas_run, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(appCanvas_extrasLabel)
                        .addGap(18, 18, 18)
                        .addComponent(appCanvas_loadPNG, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(appCanvas_imgpathlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(appCanvas_saveoption, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        appCanvas_run.getAccessibleContext().setAccessibleDescription("");

        getAccessibleContext().setAccessibleDescription("Look text or png in 3D way!");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manualTextInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualTextInputActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_manualTextInputActionPerformed

    private void appCanvas_loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appCanvas_loadActionPerformed
        // TODO add your handling code here:
        Process process = null;
        //Trim text temporarily, If its empty then throw error msg
        if(manualTextInput.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(null,"Text cannot be blank.");
        return;
        }

        if(manualTextInput.getText().length() > 10){
            JOptionPane.showMessageDialog(null,"Long messages will get distorted.","Warning",JOptionPane.WARNING_MESSAGE);
        }

        ProcessBuilder pb = new ProcessBuilder(
    "python3","Runner.py",CanvasWindowUI.SharedText_path, "0");  
        try {
            process = pb.start();
            
        } catch (Exception e) {
            // TODO: handle exception
            JOptionPane.showMessageDialog(null, e,"Error", JOptionPane.ERROR_MESSAGE);
        }
        finally{
            if(process != null) process.destroy();
        }
        try{
            //Setup a temporary config file for canvas_window

        config = new FileWriter(".config.txt");
        config.write("Halt = False\nSpeed = "+CanvasWindowUI.speed+"\nSave = "+Save);
        config.close();
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e,"Error", JOptionPane.ERROR_MESSAGE);
        };
        manualtextinputbuffer.replace(0, manualtextinputbuffer.length(), manualTextInput.getText());
        appCanvas_imgpathlabel.setText("");
        appCanvas_run.setEnabled(true);

    }//GEN-LAST:event_appCanvas_loadActionPerformed

    public void appCanvas_runActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appCanvas_runActionPerformed
        // TODO add your handling code here:
        
        canvaswindowui = new CanvasWindowUI(this);
        canvaswindowui.setVisible(true);
        
        new Thread(() -> {
        canvaswindowui.startProcess();
    }).start();
        appCanvas_run.setEnabled(false);
    }//GEN-LAST:event_appCanvas_runActionPerformed

    private void appCanvas_loadPNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appCanvas_loadPNGActionPerformed
        // TODO add your handling code here:
        LoadPNGMenu();

         int Result = chooser.showOpenDialog(appCanvas_loadPNG);
         
    if(Result == JFileChooser.APPROVE_OPTION){
        appCanvas_load.setVisible(false);
        PNGSelcted = chooser.getSelectedFile();
        appCanvas_imgpathlabel.setText("File: " + PNGSelcted.getAbsolutePath());
        chooser.setCurrentDirectory(PNGSelcted);
            try {
                PNGMode = true;
canvaswindowui = new CanvasWindowUI(this);
canvaswindowui.setVisible(true); 
canvaswindowui.revalidate();
canvaswindowui.repaint();

// Start heavy Python process in a background thread
new Thread(() -> {
    canvaswindowui.startProcess();
    PNGMode = false;
}).start();  
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Failed to load PNG canvas" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }   
    finally{
        appCanvas_load.setVisible(true);
        PNGMode = false;
    }      
    }
}//GEN-LAST:event_appCanvas_loadPNGActionPerformed

    private void appCanvas_saveoptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appCanvas_saveoptionActionPerformed
        // TODO add your handling code here:

            JOptionPane.showMessageDialog(this,"Under Development.","Mode un-reachable", JOptionPane.CLOSED_OPTION);
        return;
        /*if(canvaswindowui == null)
        {
            JOptionPane.showMessageDialog(this,"Please run animation, then use [Save as GIF].","Info",JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        //Block to update txt file:
        Save = true;
try{
    FileWriter updater = new FileWriter(".config.txt");
    BufferedWriter config = new BufferedWriter(updater);
    config.write("Halt = "+CanvasWindowUI.halt);
    config.write("\nSpeed = "+CanvasWindowUI.speed);
    config.write("\nSave = "+Save);
    config.flush();
    config.close();
    Save=false;
}catch(Exception e){
    JOptionPane.showMessageDialog(this,"Cannot save as GIF. Retry","GIF save error",JOptionPane.ERROR_MESSAGE);
}*/
    }//GEN-LAST:event_appCanvas_saveoptionActionPerformed

    //This method is used to clean UI buttons and text fields if needed.
    protected void CleanUI(){
        appCanvas_run.setEnabled(false);
        appCanvas_load.setEnabled(true);
        manualTextInput.setText("Input");
        manualtextinputbuffer.replace(0, manualtextinputbuffer.length(), "Input");
        appCanvas_imgpathlabel.setText("");
        appCanvas_saveoption.setEnabled(false);
        appCanvas_saveoption.setVisible(false);
        Save = false;
        return;
    }
    protected void LoadPNGMenu(){
    // Code to import png from a button
    chooser = new JFileChooser();
    
    FileNameExtensionFilter filter = new FileNameExtensionFilter("PNG files (*.png)", "png");
    chooser.addChoosableFileFilter(filter);
    // Disable all other file filters
    chooser.setAcceptAllFileFilterUsed(false);

    try{
            //Setup a temporary config file for canvas_window

        config = new FileWriter(".config.txt");
        config.write("Halt = False\nSpeed = "+CanvasWindowUI.speed+"\nSave = "+Save);
        config.close();
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e,"Error", JOptionPane.ERROR_MESSAGE);
        };
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainWindowUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appCanvas_extrasLabel;
    private javax.swing.JLabel appCanvas_imgpathlabel;
    public javax.swing.JButton appCanvas_load;
    private javax.swing.JButton appCanvas_loadPNG;
    public javax.swing.JButton appCanvas_run;
    private javax.swing.JButton appCanvas_saveoption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField manualTextInput;
    // End of variables declaration//GEN-END:variables
}
